import type { ActivityCandidate, MemberPlanningProfile } from "@/lib/domain/itinerary";
import type { TripSetupInput } from "@/lib/domain/trip";

export const demoTrip: TripSetupInput = {
  name: "Penang Long Weekend",
  destinationName: "George Town, Penang",
  startDate: "2026-10-03",
  endDate: "2026-10-05",
  budgetTier: "standard",
  pace: "balanced",
  baseCurrency: "MYR",
  notes: "Prioritize halal food, short transfers, and an indoor rain fallback.",
};

export const demoMembers: MemberPlanningProfile[] = [
  {
    id: "aisha",
    displayName: "Aisha",
    consentStatus: "granted",
    severeAllergies: ["peanuts"],
    accessibilityRequirements: [],
    dietaryRequirements: ["halal"],
    requiresHalal: true,
  },
  {
    id: "daniel",
    displayName: "Daniel",
    consentStatus: "pending",
    severeAllergies: [],
    accessibilityRequirements: ["step_free"],
    dietaryRequirements: [],
    requiresHalal: false,
  },
  {
    id: "mei",
    displayName: "Mei",
    consentStatus: "granted",
    severeAllergies: [],
    accessibilityRequirements: [],
    dietaryRequirements: ["vegetarian_options"],
    requiresHalal: false,
  },
];

export const demoCandidates: ActivityCandidate[] = [
  {
    id: "peranakan-mansion",
    title: "Pinang Peranakan Mansion",
    category: "culture",
    allergens: [],
    accessibilityFeatures: ["step_free"],
    dietaryOptions: [],
    halalStatus: "not_applicable",
    indoor: true,
    costTier: "standard",
    intensity: "relaxed",
    travelMinutes: 12,
    isOpen: true,
    startTime: "10:00",
    durationMinutes: 90,
  },
  {
    id: "halal-lunch",
    title: "Jawi House Lunch",
    category: "food",
    allergens: [],
    accessibilityFeatures: ["step_free"],
    dietaryOptions: ["halal", "vegetarian_options"],
    halalStatus: "verified",
    indoor: true,
    costTier: "standard",
    intensity: "relaxed",
    travelMinutes: 8,
    isOpen: true,
    startTime: "12:30",
    durationMinutes: 75,
  },
  {
    id: "clan-jetties",
    title: "Clan Jetties Walk",
    category: "culture",
    allergens: [],
    accessibilityFeatures: [],
    dietaryOptions: [],
    halalStatus: "not_applicable",
    indoor: false,
    costTier: "budget",
    intensity: "active",
    travelMinutes: 24,
    isOpen: true,
    startTime: "15:00",
    durationMinutes: 70,
  },
  {
    id: "peanut-market",
    title: "Peanut Market Tasting",
    category: "food",
    allergens: ["peanuts"],
    accessibilityFeatures: ["step_free"],
    dietaryOptions: [],
    halalStatus: "not_verified",
    indoor: true,
    costTier: "budget",
    intensity: "relaxed",
    travelMinutes: 15,
    isOpen: true,
    startTime: "16:30",
    durationMinutes: 45,
  },
  {
    id: "hin-bus-depot",
    title: "Hin Bus Depot Galleries",
    category: "culture",
    allergens: [],
    accessibilityFeatures: ["step_free"],
    dietaryOptions: [],
    halalStatus: "not_applicable",
    indoor: true,
    costTier: "budget",
    intensity: "balanced",
    travelMinutes: 18,
    isOpen: true,
    startTime: "15:30",
    durationMinutes: 75,
  },
];
