"use client";

import React, { useEffect, useState } from "react";
import { Compass, LoaderCircle } from "lucide-react";
import { GeminiProposalReview } from "@/components/gemini-proposal-review";
import type { ProposalRecord } from "@/lib/repositories/planning-repository";

type TripSnapshot = { activeProposalId: string | null; revision: number };

/**
 * The written itinerary: a plain-language summary of what the assistant has proposed for this
 * trip -- day by day, with the rationale behind each activity -- and an accept/reject decision
 * on anything still pending. Deliberately not another copy of Timeline's drag-and-drop
 * calendar: proposals are generated by asking the assistant in Chat (see shouldAddressAssistant/
 * AssistantProposalCard), and this page is where you review and confirm what it comes back
 * with, reusing the same fetch/decide flow the inline chat proposal cards already use.
 */
export function PlanView({ tripId, canDecideProposals }: {
  tripId: string;
  canDecideProposals: boolean;
}) {
  const [loading, setLoading] = useState(true);
  const [proposals, setProposals] = useState<ProposalRecord[]>([]);
  const [trip, setTrip] = useState<TripSnapshot | null>(null);
  const [decidingProposalId, setDecidingProposalId] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(`/api/trips/${encodeURIComponent(tripId)}`, { cache: "no-store" })
      .then((response) => response.json())
      .then((data) => {
        if (cancelled) return;
        setProposals(data?.proposals ?? []);
        if (data?.trip) setTrip({ activeProposalId: data.trip.activeProposalId ?? null, revision: data.trip.revision });
      })
      .catch(() => {
        // No proposals yet isn't fatal -- the empty state below covers it.
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [tripId]);

  async function handleDecision(proposalId: string, decision: "accept" | "reject") {
    setDecidingProposalId(proposalId);
    try {
      const response = await fetch(`/api/trips/${encodeURIComponent(tripId)}/proposals/${encodeURIComponent(proposalId)}/decision`, {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }),
      });
      const data = await response.json().catch(() => null);
      if (response.ok && data?.proposal) {
        setProposals((existing) => existing.map((proposal) => (proposal.id === data.proposal.id ? data.proposal : proposal)));
        if (data.proposal.status === "accepted") {
          setTrip((current) => (current ? { ...current, activeProposalId: data.proposal.id } : current));
        }
      }
    } finally {
      setDecidingProposalId(null);
    }
  }

  if (loading) {
    return <p className="inline-notice" role="status"><LoaderCircle className="spin" aria-hidden="true" />Loading the plan...</p>;
  }

  const active = proposals.find((proposal) => proposal.id === trip?.activeProposalId);
  const reviews = proposals.filter((proposal) => proposal.id !== trip?.activeProposalId);

  if (!active && reviews.length === 0) {
    return <div className="empty-state">
      <Compass aria-hidden="true" />
      <h2>No itinerary yet</h2>
      <p>Ask the assistant in Chat to put together an itinerary, then review and confirm it here.</p>
    </div>;
  }

  return <>
    {active
      ? <GeminiProposalReview proposal={active} active />
      : trip?.activeProposalId && <div className="empty-state">
          <Compass aria-hidden="true" /><h2>Active itinerary unavailable</h2><p>Reload to try again.</p>
        </div>}
    {reviews.map((proposal) => (
      <GeminiProposalReview key={proposal.id} proposal={proposal}
        canDecide={canDecideProposals} outdated={trip !== null && proposal.tripRevision !== trip.revision}
        busy={decidingProposalId === proposal.id}
        onDecision={(decision) => handleDecision(proposal.id, decision)} />
    ))}
  </>;
}
